### ISSUE TITLE
gl.GLException(f"Unable to create texture. {gl.GL_MAX_TEXTURE_SIZE} {size}") causes crash

### ISSUE THREAD

**Issue by jtrip** [kfields/badwing#1]
On a:
MacBook Pro (Retina, 13-inch, Early 2015)
2.9 GHz Intel Core i5
8 GB 1867 MHz DDR3
Intel Iris Graphics 6100 1536 MB

Running macOS Mojave 10.14.6 (18G103)

OpenGL Properties
```
OpenGL:

  Version:	17.7.3
  Obtained from:	Apple
  Last Modified:	1/23/19, 12:24 PM
  Kind:	Intel
  64-Bit (Intel):	Yes
  Signed by:	Software Signing, Apple Code Signing Certification Authority, Apple Root CA
  Get Info String:	OpenGL 17.7.3.0.0
  Location:	/System/Library/Frameworks/OpenGL.framework
  Private:	No
```

With or without any input, after about 12 seconds this exception is thrown.

```
2020-03-25 21:59:29.669 Python[68189:7658585] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/shader.py", line 521, in __init__
    self.format, gl.GL_UNSIGNED_BYTE, data
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/jtrip/Projects/pyweek/badwing/main.py", line 54, in <module>
    main()
  File "/Users/jtrip/Projects/pyweek/badwing/main.py", line 50, in main
    arcade.run()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/window_commands.py", line 250, in run
    pyglet.app.run()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/app/base.py", line 171, in run
    self._run()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/app/base.py", line 183, in _run
    timeout = self.idle()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/app/base.py", line 304, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/Users/jtrip/Projects/pyweek/badwing/main.py", line 44, in on_update
    self.level.update(dt)
  File "/Users/jtrip/Projects/pyweek/badwing/badwing/levels/level1.py", line 98, in update
    self.butterfly_layer.update_animation(delta_time)
  File "/Users/jtrip/Projects/pyweek/badwing/badwing/layer.py", line 32, in update_animation
    self.sprites.update_animation(delta_time)
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite_list.py", line 445, in update_animation
    sprite.update_animation(delta_time)
  File "/Users/jtrip/Projects/pyweek/badwing/badwing/butterfly/__init__.py", line 87, in update_animation
    self.texture = self.walk_textures[self.cur_texture // UPDATES_PER_FRAME][self.character_face_direction]
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite.py", line 696, in _set_texture2
    sprite_list.update_texture(self)
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite_list.py", line 749, in update_texture
    self._calculate_sprite_buffer()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite_list.py", line 680, in _calculate_sprite_buffer
    _calculate_sub_tex_coords()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite_list.py", line 637, in _calculate_sub_tex_coords
    texture_bytes
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/shader.py", line 545, in texture
    return Texture(size, component, data)
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/shader.py", line 524, in __init__
    raise gl.GLException(f"Unable to create texture. {gl.GL_MAX_TEXTURE_SIZE} {size}")
pyglet.gl.lib.GLException: Unable to create texture. 3379 (16512, 96)
```
(In the constructor of the Texture class in the shader module)

I will try to reproduce elsewhere.

**Comment by jtrip** [comment]
Running outside of pycharm produces the same but here is the traceback unaltered by an ide
```
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    main()
  File "main.py", line 50, in main
    arcade.run()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/window_commands.py", line 250, in run
    pyglet.app.run()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/app/base.py", line 171, in run
    self._run()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/app/base.py", line 183, in _run
    timeout = self.idle()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/app/base.py", line 304, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/pyglet/clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "main.py", line 44, in on_update
    self.level.update(dt)
  File "/Users/jtrip/Projects/pyweek/badwing/badwing/levels/level1.py", line 98, in update
    self.butterfly_layer.update_animation(delta_time)
  File "/Users/jtrip/Projects/pyweek/badwing/badwing/layer.py", line 32, in update_animation
    self.sprites.update_animation(delta_time)
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite_list.py", line 445, in update_animation
    sprite.update_animation(delta_time)
  File "/Users/jtrip/Projects/pyweek/badwing/badwing/butterfly/__init__.py", line 87, in update_animation
    self.texture = self.walk_textures[self.cur_texture // UPDATES_PER_FRAME][self.character_face_direction]
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite.py", line 696, in _set_texture2
    sprite_list.update_texture(self)
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite_list.py", line 749, in update_texture
    self._calculate_sprite_buffer()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite_list.py", line 680, in _calculate_sprite_buffer
    _calculate_sub_tex_coords()
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/sprite_list.py", line 637, in _calculate_sub_tex_coords
    texture_bytes
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/shader.py", line 545, in texture
    return Texture(size, component, data)
  File "/Users/jtrip/Projects/pyweek/badwing/env/lib/python3.7/site-packages/arcade/shader.py", line 524, in __init__
    raise gl.GLException(f"Unable to create texture. {gl.GL_MAX_TEXTURE_SIZE} {size}")
pyglet.gl.lib.GLException: Unable to create texture. 3379 (16512, 96)
```

**Comment by kfields** [comment]
I think I'm using too much texture memory for the butterflies.  Hold off on further testing until I get back to you.  I'm going to either stick them in a sprite sheet or find a different sprite pack.
Thanks a bunch!!!

**Comment by jtrip** [comment]
putting a breakpoint on line 445 of `env/lib/python3.7/site-packages/arcade/sprite_list.py` shows that the sprites in question are the 8 butterflies.
`<badwing.butterfly.ButterflySprite object at 0x120c35278>`

**Comment by kfields** [comment]
It was me.  Fixed: [https://github.com/kfields/badwing/commit/fa9de35dda2a35063bb58df71cb4f056c39fc52c](https://github.com/kfields/badwing/commit/fa9de35dda2a35063bb58df71cb4f056c39fc52c)

**Comment by kfields** [comment]
I was wrong.  I tested it on my other laptop and it worked flawlessly.  Changed the code and pushed from this machine and now it's doing it again.  Hmmm....

**Comment by kfields** [comment]
I changed frames to 8.  Seems to have fixed it.
I copy pasted that code from arcade, so ...
Let me know if you have any further problems
Thanks!
